# Generated by Django 4.0 on 2021-12-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='q1FakeAnswers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2FakeAnswers',
        ),
    ]
