# Generated by Django 4.0 on 2021-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_q1fakeanswers_remove_quiz_q2fakeanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='q1Correction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q2Correction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q3Answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q3Correction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q3Question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
