# Generated by Django 4.0 on 2021-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_q1correction_quiz_q2correction_quiz_q3answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='q1Correction',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2Correction',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q3Correction',
        ),
        migrations.AddField(
            model_name='quiz',
            name='q1Explanation',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q2Explanation',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q3Explanation',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
